// Définition des classes et des informations
final List<String> classNames = [
  'Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy',
  'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 
  'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 
  'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 
  'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 
  'Grape___healthy', 'Non_leaves', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot',
  'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 
  'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 
  'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 
  'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 
  'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 
  'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 
  'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus',
  'Tomato___healthy'
];

final Map<String, String> plantDiseaseInfo = {
  'Apple___Apple_scab': "La tavelure du pommier est une maladie fongique causant des lésions sombres sur les feuilles et les fruits, réduisant leur qualité.",
    'Apple___Black_rot': "La pourriture noire du pommier provoque des taches sombres sur les fruits et les branches, causée par un champignon.",
    'Apple___Cedar_apple_rust': "La rouille du cèdre-pommier est une maladie fongique nécessitant des cèdres pour compléter son cycle.",
    'Apple___healthy': "Ce pommier est en bonne santé, sans signe de maladie.",
    'Blueberry___healthy': "Cette myrtille est en bonne santé.",
    'Cherry_(including_sour)___Powdery_mildew': "L'oïdium des cerises est une maladie fongique provoquant un dépôt poudreux blanc sur les feuilles.",
    'Cherry_(including_sour)___healthy': "Ces cerises sont en bonne santé.",
    'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot': "Les taches foliaires à Cercospora affectent les feuilles du maïs, réduisant la photosynthèse et les rendements.",
    'Corn_(maize)___Common_rust_': "La rouille commune du maïs est une maladie fongique causant des pustules rouges sur les feuilles.",
    'Corn_(maize)___Northern_Leaf_Blight': "La brûlure septentrionale des feuilles est une maladie causée par un champignon, affectant les feuilles de maïs.",
    'Corn_(maize)___healthy': "Ce maïs est en bonne santé.",
    'Grape___Black_rot': "La pourriture noire de la vigne cause des lésions brunes et des fruits pourris, réduisant la production.",
    'Grape___Esca_(Black_Measles)': "L'Esca de la vigne provoque des taches noires sur les feuilles et des pertes de production.",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': "La brûlure des feuilles de vigne entraîne des taches brunes et la défoliation des plants.",
    'Grape___healthy': "Cette vigne est en bonne santé.",
    'Non_leaves': "L'image que vous avez sélectionné ne correspond peut-être à une feuilles.",
    'Orange___Haunglongbing_(Citrus_greening)': "Le Huanglongbing est une maladie bactérienne grave provoquant le verdissement des agrumes et la chute des fruits.",
    'Peach___Bacterial_spot': "La tache bactérienne du pêcher cause des lésions sur les fruits et les feuilles.",
    'Peach___healthy': "Ce pêcher est en bonne santé.",
    'Pepper,_bell___Bacterial_spot': "La tache bactérienne du poivron provoque des taches brunes sur les feuilles et les fruits.",
    'Pepper,_bell___healthy': "Ce poivron est en bonne santé.",
    'Potato___Early_blight': "L'alternariose de la pomme de terre provoque des taches brunes en cibles sur les feuilles.",
    'Potato___Late_blight': "Le mildiou de la pomme de terre est une maladie dévastatrice causant des lésions aqueuses sur les feuilles et les tubercules.",
    'Potato___healthy': "Cette pomme de terre est en bonne santé.",
    'Raspberry___healthy': "Cette framboise est en bonne santé.",
    'Soybean___healthy': "Ce soja est en bonne santé.",
    'Squash___Powdery_mildew': "L'oïdium de la courge provoque un dépôt blanc poudreux sur les feuilles.",
    'Strawberry___Leaf_scorch': "La brûlure des feuilles de fraise entraîne un dessèchement et une décoloration des feuilles.",
    'Strawberry___healthy': "Cette fraise est en bonne santé.",
    'Tomato___Bacterial_spot': "La tache bactérienne de la tomate cause des lésions brunes sur les feuilles et les fruits.",
    'Tomato___Early_blight': "L'alternariose de la tomate provoque des taches circulaires brunes sur les feuilles et les fruits.",
    'Tomato___Late_blight': "Le mildiou de la tomate cause des lésions aqueuses sur les feuilles et les fruits.",
    'Tomato___Leaf_Mold': "Le moisi des feuilles de tomate provoque des taches jaunes sur le dessus des feuilles.",
    'Tomato___Septoria_leaf_spot': "La tache septorienne des feuilles de tomate cause des taches brunes avec un centre clair sur les feuilles.",
    'Tomato___Spider_mites Two-spotted_spider_mite': "Les acariens à deux points provoquent une décoloration et une chute des feuilles de tomate.",
    'Tomato___Target_Spot': "La tache cible de la tomate provoque des lésions nécrotiques sur les feuilles.",
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': "Ce virus provoque des feuilles jaunes enroulées et un ralentissement de la croissance.",
    'Tomato___Tomato_mosaic_virus': "Le virus de la mosaïque de la tomate cause des taches jaunes et une déformation des feuilles.",
    'Tomato___healthy': "Cette tomate est en bonne santé."
};

final Map<String, String> classAdvice = {
  'Apple___Apple_scab': ": Retirez les feuilles affectées et éliminez-les correctement pour éviter leur propagation.",
    'Apple___Black_rot': ": Retirez les fruits et les feuilles infectés et traitez avec un fongicide.",
    'Apple___Cedar_apple_rust': ": Taillez les branches affectées et utilisez un fongicide.",
    'Apple___healthy': ": Votre pommier a l'air en bonne santé ! Continuez à lui prodiguer de bons soins.",
    'Blueberry___healthy': ": Votre bleuet est en bonne santé ! Assurez-lui un arrosage et un ensoleillement adéquats.",
    'Cherry_(including_sour)___Powdery_mildey': ": Traitez avec des fongicides et retirez les feuilles infectées.",
    'Cherry_(including_sour)___healthy': ": Votre cerisier est en bonne santé ! Surveillez sa croissance.",
    'Corn_(maize)___Cercospora_leaf_spot_gray_leaf_spot': ": Appliquez un fongicide et retirez les feuilles affectées feuilles.",
    'Corn_(maize)___Common_rust_': ": Utilisez un fongicide et améliorez la circulation de l'air autour de la plante.",
    'Corn_(maize)___Northern_Leaf_Blight': ": Retirez les feuilles infectées et appliquez des fongicides.",
    'Corn_(maize)___healthy': ": Votre maïs est en bonne santé ! Continuez l'irrigation et la gestion des ravageurs.",
    'Grape___Black_rot': ": Taillez les vignes infectées et appliquez des fongicides.",
    'Grape___Esca_(Black_Measles)': ": Retirez les vignes infectées et traitez avec des fongicides appropriés.",
    'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)': ": Retirez les feuilles infectées et appliquez des fongicides.",
    'Grape___healthy': ": Votre vigne est en bonne santé ! Assurez un ensoleillement et un arrosage adéquats.",
    'Non_leaves': "Réessayez en sélectionnant l'image à nouveau ou une autre.",
    'Orange___Haunglongbing_(Citrus_greening)': ": Il s'agit d'une maladie grave. Retirez les arbres affectés et désinfectez les outils.",
    'Peach___Bacterial_spot': ": Taillez les branches affectées et appliquez des fongicides à base de cuivre.",
    'Peach___healthy': ": Votre pêcher est en bonne santé ! Continuez les soins réguliers.",
    'Pepper,_bell___Bacterial_spot': ": Retirez les feuilles infectées et utilisez des bactéricides.",
    'Pepper,_bell___healthy': ": Votre plant de poivron a l'air en bonne santé ! Gardez le sol bien drainé.",
    'Potato___Early_blight': ": Appliquez des fongicides et retirez les feuilles infectées.",
    'Potato___Late_blight': ": Retirez les plantes infectées et appliquez un fongicide pour empêcher toute propagation ultérieure.",
    'Potato___healthy': ": Vos plants de pommes de terre sont en bonne santé ! Assurez un bon drainage du sol.",
    'Raspberry___healthy': ": Votre plant de framboisier est en bonne santé ! Continuez les soins réguliers.",
    'Soybean___healthy': ": Votre plant de soja est en bonne santé ! Assurez un espacement approprié pour la croissance.",
    'Squash___Powdery_mildew': ": Traitez avec un fongicide et retirez les feuilles infectées.",
    'Strawberry___Leaf_scorch': ": Taillez les feuilles affectées et améliorez la gestion de l'eau.",
    'Strawberry___healthy': ": Votre plant de fraisier est en bonne santé ! Gardez le sol fertile.",
    'Tomato___Bacterial_spot': ": Taillez les zones infectées et appliquez des fongicides à base de cuivre.",
    'Tomato___Early_blight': ": Appliquez un fongicide et retirez les feuilles affectées.",
    'Tomato___Late_blight': ": Retirez les plantes infectées et appliquez des fongicides.",
    'Tomato___Leaf_Mold': ": Améliorez la ventilation autour de la plante et traitez avec des fongicides.",
    'Tomato___Septoria_leaf_spot': ": Retirez les feuilles affectées et appliquez des fongicides.",
    'Tomato___Spider_mites Two-spotted_spider_mite': ": Appliquez des acaricides et retirez les feuilles infestées.",
    'Tomato___Target_Spot': ": Appliquez des fongicides et retirez les feuilles infectées.",
    'Tomato___Tomato_Yellow_Leaf_Curl_Virus': ": Retirez les feuilles infectées plantes et contrôlez les pucerons.",
    'Tomato___Tomato_mosaic_virus': ": Retirez les plantes infectées et désinfectez les outils.",
    'Tomato___healthy': ": Votre plante de tomates a l'air en bonne santé ! Continuez les soins réguliers."
};
